### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by ghost** [xiaocheng555/vue-tabs-cache#1]
从多级缓存页面中的tab2点击左侧导航再次点回来会出现无法缓存的问题，希望作者大大可以解决，十分支持

**Comment by xiaocheng555** [comment]
> 从多级缓存页面中的tab2点击左侧导航再次点回来会出现无法缓存的问题，希望作者大大可以解决，十分支持

好的，我看看

**Comment by xiaocheng555** [comment]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/19643785/224266820-1022f768-4740-44c0-9a0c-d2b7cb906ff8.png">
这里改为：
<img width="984" alt="image" src="https://user-images.githubusercontent.com/19643785/224267045-ffcdf2ac-c118-4d83-9d77-217982db3dac.png">

这里判断 props.tabRouteViewDepth === matched.length 必须是跟tab同级路由，否则会影响多级路由缓存

**Comment by xiaocheng555** [comment]
> 从多级缓存页面中的tab2点击左侧导航再次点回来会出现无法缓存的问题，希望作者大大可以解决，十分支持

已修复
