### ISSUE TITLE
tabRouteViewDepth prop 是否可以直接用最后一级

### ISSUE THREAD

**Issue by SublimeCT** [xiaocheng555/vue-tabs-cache#3]
https://github.com/xiaocheng555/vue-tabs-cache/blob/2f6ac0d66ab8b7ded820458f04cece40fe9d1b90/vue3/src/layout/LayoutTabs.vue#LL33C10-L33C10

这里的 `tabRouteViewDepth` 默认是 `2`, 好像可以直接用最有一项的, 这里为啥要加这个 `prop`, 什么情况下需要传 `tabRouteViewDepth`

**Comment by xiaocheng555** [comment]
tab页内嵌套了多层路由时, 此时最后一层拿到的就是嵌套内的路由,而不是tab所有在的路由

**Comment by xiaocheng555** [comment]
> tab页内嵌套了多层路由时, 此时最后一层拿到的就是嵌套内的路由,而不是tab所有在的路由

tab页内嵌套了多层路由时, 此时最后一层拿到的就是嵌套内的路由,而不是tab所有在的路由

**Comment by SublimeCT** [comment]
ok 理解了, 感谢解答
